#!/bin/bash

#SBATCH -J Serial           # Job name
#SBATCH -o Serial.o%j       # Name of stdout output file
#SBATCH -e Serial.e%j       # Name of stderr error file
#SBATCH -p normal          # Queue (partition) name
#SBATCH -N 1              # Total # of nodes 
#SBATCH -n 1             # Total # of mpi tasks
#SBATCH -t 01:30:00        # Run time (hh:mm:ss)
#SBATCH -A CMPS-5433-MWSU  # class project/account code

# Other commands must follow all #SBATCH directives...

module list
pwd
date

# Launch Serial Code

./Serial.exe         

# ---------------------------------------------------