#!/bin/bash

#SBATCH -J NoThreads           # Job name
#SBATCH -o NoThreads.o%j       # Name of stdout output file
#SBATCH -e NoThreads.e%j       # Name of stderr error file
#SBATCH -p normal          # Queue (partition) name
#SBATCH -N 1               # Total # of nodes 
#SBATCH -n 1            # Total # of mpi tasks
#SBATCH -t 01:30:00        # Run time (hh:mm:ss)
#SBATCH --mail-user=
#SBATCH --mail-type=all    # Send email at begin and end of job
#SBATCH -A CMPS-5433-MWSU  # class project/account code

# Other commands must follow all #SBATCH directives...

module list
pwd
date

./NoThreads.exe
# ---------------------------------------------------