#!/bin/bash

#SBATCH -J CipherParallel # Job name
#SBATCH -o CipherParallel.o%j       # Name of stdout output file
#SBATCH -e CipherParallel.e%j       # Name of stderr error file
#SBATCH -p normal          # Queue (partition) name
#SBATCH -N 1               # Total # of nodes 
#SBATCH -n 1              # Total # of mpi tasks
#SBATCH -t 01:30:00        # Run time (hh:mm:ss)
#SBATCH -A CMPS-5433-MWSU  # class project/account code
module list
pwd
date
export OMP_NUM_THREADS=16 #how many threads needed
./CipherParallel.exe 

# ---------------------------------------------------